baseURL: "https://jerryren527.github.io"
languageCode: "en-us"
title: "Jerry Ren"
theme: hugo-profile

# Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: resume
      name: Resume
      # title: Blog posts
      url: "https://drive.google.com/file/d/1W5AnTRMEY4jKqLlk5oGJW27GQd1LFfrS/view?usp=sharing"
      weight: 1
    
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Jerry Ren"
  # description: Text about my personal website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/code.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    # intro: "Hi, I'm"
    title: "Hi, I'm Jerry!"
    subtitle: "I am a computer science graduate and aspiring software engineer."
    # content: "A Computer Science graduate from Stony Brook University. Learning constatnly and"
    # image: /images/hero.svg
    image: "/me.jpg"
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1W5AnTRMEY4jKqLlk5oGJW27GQd1LFfrS/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jerryren527
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jerry-ren21
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    # image: "/me.jpg"
    content: |-
      I’m a computer science graduate with in-depth experience in full-stack development and data analysis. My main tech stack is Python and Django for the back-end and JavaScript, HTML, and CSS for the front-end. I also have experience using MongoDB, Express, React, and Nodejs for making web apps. For data analysis, Python and SQL are my go-to tools. I believe in lifelong learning (currently learning machine learning), so I love the endless learning possibilities in technology.

      I’m curious and analytical - I ask questions, explore answers, and constantly seek new challenges.

      I am technology-driven - I stay on the edge of what’s new and exciting and how those tools can build solutions.

      I am communicative, collaborative, and team-oriented - I thrive in a collaborative team environment.

    skills:
      enable: true
      title: "Here are some technologies that I work with:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node.js"
        - "Express"
        - "Python"
        - "C/C++"
  projects:
    enable: true
    items:
      - title: Covid-19 Dashboard
        content: A web application that visualizes Covid-19 data queried from BigQuery.
        image: 'covid.png'
        featured:
          name: Demo
          link: https://jerryren527-covid-19-dashboard-1--home-n36ijl.streamlitapp.com
        badges:
          - "Python"
          - "BigQuery"
      
      - title: Telephone System Simulator
        content: A server that simulates the behavior of a private branch exchange telephone system.
        image: 'telephone.jpg'
        featured:
          name: Github Repo
          link: https://github.com/jerryren527/pbx
        badges:
          - "C"
          # - "Bootstrap"
          # - "Javascript"
        # badges:
          # - "Hugo"
          # - "Bootstrap"
          # - "Javascript"
        # links:
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: MUSH Interpreter
        content: A simple scripting language interpreter for the MUSH programming language, a language roughly inspired by the BASIC language.
        image: 'mush.png'
        featured:
          name: Github Repo
          link: https://github.com/jerryren527/mush-interpreter
        badges:
          - "C"
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

      - title: Dynamic Memory Allocator
        content: A dynamic memory allocator for the x84-64 architecture.
        image: 'cpu.jpg'
        featured:
          name: Github Repo
          link: https://github.com/jerryren527/dynamic_memory_allocator
        badges:
          - "C"
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/HugoProfileV2
      
      - title: SBU Pathways
        content: A web application for tracking the degree progress of Stony Brook University Master's students.
        image: 'pathways.png'
        featured:
          name: Demo
          link: https://sbu-pathways.netlify.app
        badges:
          - "JavaScript"
          - "React"
          - "NodeJS"
      



  #Contact
  contact:
    enable: true
    content: If you would like to contact me, feel free to send me an email!
    email: jerryren.5279@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/jerryren527
      linkedin: https://www.linkedin.com/in/jerry-ren21
